### PR TITLE
Homework 17

### PR DESCRIPTION
**Pull request by TetianaZaikina**
Dear teacher, I am totally lost!

### CODE REVIEW

**Comment by Berichicko** [comment]
The code is not compiled! Please finish the homework!You got this problem, please correct it. 

image

HINT

Dear Tetiana

I will try to help you again

Please download this code and see the solution https://drive.google.com/file/d/1WDlc4i5nuXTg0MbgduD1KY9H_of8CZyH/view?usp=sharing

or

**Step 1**

```
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;
import java.time.Duration;

public class BaseTest {

    // Variable Declarations
    public WebDriver driver = null;
    public String url = "https://qa.koel.app/";

    // Preparation before starting the test suite
    @BeforeSuite
    void setupClass() {
        WebDriverManager.chromedriver().setup();
    }

    // Launching the browser before each test
    @BeforeMethod
    public void launchBrowser() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);

        // Setting the implicit wait time
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));

        // Maximizing the browser window
        driver.manage().window().maximize();
    }

    // Closing the browser after each test
    @AfterMethod
    public void closeBrowser() {
        driver.quit();
    }

    // Navigating to the specified page
    public void navigateToPage() {
        driver.get(url);
    }

    // Providing the email address
    public void provideEmail(String email) {
        WebElement emailField = driver.findElement(By.cssSelector("input[type='email']"));
        emailField.clear();
        emailField.sendKeys(email);
    }

    // Providing the password
    public void providePassword(String password) {
        WebElement passwordField = driver.findElement(By.cssSelector("input[type='password']"));
        passwordField.clear();
        passwordField.sendKeys(password);
    }

    // Clicking the "Submit" button
    public void clickSubmit() {
        WebElement submit = driver.findElement(By.cssSelector("button[type='submit']"));
        submit.click();
    }
}
```

**Step 2**

```
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.Assert;
import org.testng.annotations.Test;

public class Homework17 extends BaseTest {
    @Test
    public void addSongToPlaylist() throws InterruptedException {
        String expectedSongAddedMessage = "Added 1 song into \"Test Pro Playlist.\"";

        // Navigate to the page
        navigateToPage();
        
        // Input email and password
        provideEmail("demo@class.com");
        providePassword("te$t$tudent");
        clickSubmit();
        Thread.sleep(2000);

        // Search for the song and view all results
        searchSong("Song");
        clickViewAllBtn();

        // Select the first song from the results
        selectFirstSongResult();

        // Click the "Add to Playlist" button
        clickAddToBtn();

        // Choose the playlist
        choosePlaylist();

        // Check the success message for adding the song to the playlist
        Assert.assertEquals(getAddToPlaylistSuccessMsg(), expectedSongAddedMessage);
    }

    // Search for a song
    public void searchSong(String name) throws InterruptedException {
        WebElement searchField = driver.findElement(By.cssSelector("div#searchForm input[type='search']"));
        searchField.sendKeys(name);
        Thread.sleep(2000);
    }

    // Click the "View All" button
    public void clickViewAllBtn() throws InterruptedException {
        WebElement viewAll = driver.findElement(By.xpath("//button[@data-test='view-all-songs-btn']"));
        viewAll.click();
        Thread.sleep(2000);
    }

    // Select the first song from the results
    public void selectFirstSongResult() throws InterruptedException {
        WebElement firstSong = driver.findElement(By.xpath("//section[@id='songResultsWrapper']//tr[@class='song-item'][1]"));
        firstSong.click();
        Thread.sleep(2000);
    }

    // Click the "Add to Playlist" button
    public void clickAddToBtn() throws InterruptedException {
        WebElement addToButton = driver.findElement(By.xpath("//section[@id='songResultsWrapper']//button[@data-test='add-to-btn']"));
        addToButton.click();
        Thread.sleep(2000);
    }

    // Choose the playlist
    public void choosePlaylist() throws InterruptedException {
        // We created a playlist with the name "Test Pro Playlist"
        WebElement playlist = driver.findElement(By.xpath("//section[@id='songResultsWrapper']//li[contains(text(),'Test Pro Playlist')]"));
        playlist.click();
        Thread.sleep(2000);
    }

    // Get the text of the success message for adding to playlist
    public String getAddToPlaylistSuccessMsg() {
        WebElement notification = driver.findElement(By.cssSelector("div.success.show"));
        return notification.getText();
    }
}
```

**Step 3**

Del symbol +

image


```
public class LoginTests extends BaseTest {
    @Test
    public void loginEmptyEmailPassword() {
//      Added ChromeOptions argument below to fix websocket error
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        WebDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));

        String url = "https://qa.koel.app/";
        driver.get(url);
        Assert.assertEquals(driver.getCurrentUrl(), url);
        driver.quit();
     
    }
}
```

**Comment by TetianaZaikina** [comment]
Hello Alex,I wanted to thank you for your help and detailed explanations about the code.As you see I'm struggling and falling far behind the class. So far I've managed to do only the log in test myself. I've rewatched lesson17 4 times, rewrote the code ( still got 2 mistakes).I do not understand why all code info erases after I create a new branch.Thanks a lot,Tetiana 
Sent from Yahoo Mail on Android 
 
  On Thu, Aug 24, 2023 at 4:28 PM, Aliaksandr (Alex) ***@***.***> wrote:   


The code is not compiled! Please finish the homework!You got this problem, please correct it.



HINT

Dear Tetiana

I will try to help you again

Please download this code and see the solution https://drive.google.com/file/d/1WDlc4i5nuXTg0MbgduD1KY9H_of8CZyH/view?usp=sharing

or

Step 1
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;
import java.time.Duration;

public class BaseTest {

    // Variable Declarations
    public WebDriver driver = null;
    public String url = "https://qa.koel.app/";

    // Preparation before starting the test suite
    @BeforeSuite
    void setupClass() {
        WebDriverManager.chromedriver().setup();
    }

    // Launching the browser before each test
    @BeforeMethod
    public void launchBrowser() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);

        // Setting the implicit wait time
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));

        // Maximizing the browser window
        driver.manage().window().maximize();
    }

    // Closing the browser after each test
    @AfterMethod
    public void closeBrowser() {
        driver.quit();
    }

    // Navigating to the specified page
    public void navigateToPage() {
        driver.get(url);
    }

    // Providing the email address
    public void provideEmail(String email) {
        WebElement emailField = driver.findElement(By.cssSelector("input[type='email']"));
        emailField.clear();
        emailField.sendKeys(email);
    }

    // Providing the password
    public void providePassword(String password) {
        WebElement passwordField = driver.findElement(By.cssSelector("input[type='password']"));
        passwordField.clear();
        passwordField.sendKeys(password);
    }

    // Clicking the "Submit" button
    public void clickSubmit() {
        WebElement submit = driver.findElement(By.cssSelector("button[type='submit']"));
        submit.click();
    }
}

Step 2
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.Assert;
import org.testng.annotations.Test;

public class Homework17 extends BaseTest {
    @Test
    public void addSongToPlaylist() throws InterruptedException {
        String expectedSongAddedMessage = "Added 1 song into \"Test Pro Playlist.\"";

        // Navigate to the page
        navigateToPage();
        
        // Input email and password
        ***@***.***");
        providePassword("te$t$tudent");
        clickSubmit();
        Thread.sleep(2000);

        // Search for the song and view all results
        searchSong("Song");
        clickViewAllBtn();

        // Select the first song from the results
        selectFirstSongResult();

        // Click the "Add to Playlist" button
        clickAddToBtn();

        // Choose the playlist
        choosePlaylist();

        // Check the success message for adding the song to the playlist
        Assert.assertEquals(getAddToPlaylistSuccessMsg(), expectedSongAddedMessage);
    }

    // Search for a song
    public void searchSong(String name) throws InterruptedException {
        WebElement searchField = driver.findElement(By.cssSelector("div#searchForm input[type='search']"));
        searchField.sendKeys(name);
        Thread.sleep(2000);
    }

    // Click the "View All" button
    public void clickViewAllBtn() throws InterruptedException {
        WebElement viewAll = ***@***.***='view-all-songs-btn']"));
        viewAll.click();
        Thread.sleep(2000);
    }

    // Select the first song from the results
    public void selectFirstSongResult() throws InterruptedException {
        WebElement firstSong = ***@***.******@***.***='song-item'][1]"));
        firstSong.click();
        Thread.sleep(2000);
    }

    // Click the "Add to Playlist" button
    public void clickAddToBtn() throws InterruptedException {
        WebElement addToButton = ***@***.******@***.***='add-to-btn']"));
        addToButton.click();
        Thread.sleep(2000);
    }

    // Choose the playlist
    public void choosePlaylist() throws InterruptedException {
        // We created a playlist with the name "Test Pro Playlist"
        WebElement playlist = ***@***.***='songResultsWrapper']//li[contains(text(),'Test Pro Playlist')]"));
        playlist.click();
        Thread.sleep(2000);
    }

    // Get the text of the success message for adding to playlist
    public String getAddToPlaylistSuccessMsg() {
        WebElement notification = driver.findElement(By.cssSelector("div.success.show"));
        return notification.getText();
    }
}

Step 3

Del symbol +


public class LoginTests extends BaseTest {
    @Test
    public void loginEmptyEmailPassword() {
//      Added ChromeOptions argument below to fix websocket error
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        WebDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));

        String url = "https://qa.koel.app/";
        driver.get(url);
        Assert.assertEquals(driver.getCurrentUrl(), url);
        driver.quit();
     
    }
}

**Comment by Berichicko** [comment]
> Hello Alex,I wanted to thank you for your help and detailed explanations about the code.As you see I'm struggling and falling far behind the class. So far I've managed to do only the log in test myself. I've rewatched lesson17 4 times, rewrote the code ( still got 2 mistakes).I do not understand why all code info erases after I create a new branch.Thanks a lot,Tetiana

Hello Tetiana,

I'm glad to hear from you, and you're very welcome! 

To save your code, you need to commit and push it to the remote repository. The git commit command saves changes in the local branch, while the git push command sends changes to the remote repository. If you switch to a new branch, your code will not be deleted if you have committed and pushed your changes on the previous branch. The git push command sends changes to the remote repository, where they will be available for all branches. If you switch to a different branch, you can get the changes you sent on the previous branch by using the git pull command.

For example


https://github.com/Test-Pro-Bootcamp/A49-QA-Automation-Framework/assets/104761482/b2d02bf7-5be2-4f59-9441-7147f762e4df



Please, re-submit homework 17 for review in LMS

**Comment by TetianaZaikina** [comment]
Alex, thank you for explanation! I got it now. I appreciate your time and effort in teaching me!It takes some time to start understanding the code...long time... :)Tetiana 

Sent from Yahoo Mail on Android 
 
  On Fri, Sep 1, 2023 at 11:43 AM, Aliaksandr (Alex) ***@***.***> wrote:   



Hello Alex,I wanted to thank you for your help and detailed explanations about the code.As you see I'm struggling and falling far behind the class. So far I've managed to do only the log in test myself. I've rewatched lesson17 4 times, rewrote the code ( still got 2 mistakes).I do not understand why all code info erases after I create a new branch.Thanks a lot,Tetiana


Hello Tetiana,

I'm glad to hear from you, and you're very welcome!

To save your code, you need to commit and push it to the remote repository. The git commit command saves changes in the local branch, while the git push command sends changes to the remote repository. If you switch to a new branch, your code will not be deleted if you have committed and pushed your changes on the previous branch. The git push command sends changes to the remote repository, where they will be available for all branches. If you switch to a different branch, you can get the changes you sent on the previous branch by using the git pull command.

For example

https://github.com/Test-Pro-Bootcamp/A49-QA-Automation-Framework/assets/104761482/b2d02bf7-5be2-4f59-9441-7147f762e4df

Please, re-submit homework 17 for review in LMS

**Pull request closed without merging**
