### PR TITLE
Homework 17

### PR DESCRIPTION
**Pull request by CamdenBertrand**
created "add song to playlist test".

### CODE REVIEW

**Comment by Berichicko** [comment]
**Please finish the Homework #17:TestNG Overview**

1. Create a new branch named homework-17.

2. Create a new file, **Homework17.java** in IntelliJ IDEA.

3. Create a test case, addSongToPlaylist() using @Test annotation
and the helper/reusable methods we created.

4. Navigate to "https://qa.koel.app/".

5. Log in with your credentials.

6. Search for a song (choose any song of your choice).

7. Click View All to display the search results.

8. Click the first song in the search results.

9. Click ADD TO...

10. Choose the playlist to add it to, (we can create a new one with a unique name).

11. Verify that the notification message appears.

12. Verify that notification message has the text, "Added 1 song into {your playlist}".

13. Commit your changes to the new branch homework-17.

14. Push your code to the remote repository.

15. Create a pull request.

**Comment by CamdenBertrand** [comment]
I am unclear on what is missing from this. my test does all of these things.

**Comment by Berichicko** [comment]
> I am unclear on what is missing from this. my test does all of these things.

Hello

Please, re-submit homework for review

**Comment by CamdenBertrand** [comment]
> > I am unclear on what is missing from this. my test does all of these things.
> 
> Hello
> 
> Please, re-submit homework for review

i have resubmitted!

**Comment by Berichicko** [comment]
! Please finish the Homework #17:TestNG Overview

**Please follow the steps:**

1. Create a new branch named homework-17.

2. **Create a new file, Homework17.java in IntelliJ IDEA.**

You code:

image

3. Create a test case, addSongToPlaylist() using @Test annotation
and the helper/reusable methods we created.

4. Navigate to "https://qa.koel.app/".

5. Log in with your credentials.

6. Search for a song (choose any song of your choice).

7. Click View All to display the search results.

8. Click the first song in the search results.

9. Click ADD TO...

10. Choose the playlist to add it to, (we can create a new one with a unique name).

11. Verify that the notification message appears.

12. Verify that notification message has the text, "Added 1 song into {your playlist}".

13. Commit your changes to the new branch homework-17.

14. Push your code to the remote repository.

15. Create a pull request.

Sorry, but you have not created Homework17.java and the homework is not done

image

image

**Pull request closed without merging**
